// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package goser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type AllTodoResponse struct {
	Todos                []*TodoResponse `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AllTodoResponse) Reset()         { *m = AllTodoResponse{} }
func (m *AllTodoResponse) String() string { return proto.CompactTextString(m) }
func (*AllTodoResponse) ProtoMessage()    {}
func (*AllTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *AllTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTodoResponse.Unmarshal(m, b)
}
func (m *AllTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTodoResponse.Marshal(b, m, deterministic)
}
func (m *AllTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTodoResponse.Merge(m, src)
}
func (m *AllTodoResponse) XXX_Size() int {
	return xxx_messageInfo_AllTodoResponse.Size(m)
}
func (m *AllTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllTodoResponse proto.InternalMessageInfo

func (m *AllTodoResponse) GetTodos() []*TodoResponse {
	if m != nil {
		return m.Todos
	}
	return nil
}

type TodoRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoRequest) Reset()         { *m = TodoRequest{} }
func (m *TodoRequest) String() string { return proto.CompactTextString(m) }
func (*TodoRequest) ProtoMessage()    {}
func (*TodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *TodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoRequest.Unmarshal(m, b)
}
func (m *TodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoRequest.Marshal(b, m, deterministic)
}
func (m *TodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoRequest.Merge(m, src)
}
func (m *TodoRequest) XXX_Size() int {
	return xxx_messageInfo_TodoRequest.Size(m)
}
func (m *TodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoRequest proto.InternalMessageInfo

func (m *TodoRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TodoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (m *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(m, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "todoPackage.EmptyRequest")
	proto.RegisterType((*AllTodoResponse)(nil), "todoPackage.AllTodoResponse")
	proto.RegisterType((*TodoRequest)(nil), "todoPackage.TodoRequest")
	proto.RegisterType((*TodoResponse)(nil), "todoPackage.TodoResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x69, 0x5d, 0x05, 0xa7, 0xcb, 0x0a, 0x39, 0xd5, 0x45, 0xa4, 0xf6, 0xb4, 0x17, 0x53,
	0xa8, 0x4f, 0xb0, 0x0b, 0x7a, 0x96, 0xe8, 0xc9, 0x5b, 0xda, 0x0c, 0x6d, 0xb1, 0x75, 0x6a, 0x32,
	0x05, 0x7d, 0x0c, 0xdf, 0x58, 0x9a, 0x5d, 0xb4, 0x15, 0xf7, 0x36, 0x49, 0xbe, 0x2f, 0x33, 0xf3,
	0x03, 0x30, 0x19, 0x92, 0xbd, 0x25, 0x26, 0x11, 0x8d, 0xf5, 0xa3, 0x2e, 0x5f, 0x75, 0x85, 0xe9,
	0x0a, 0x96, 0xf7, 0x5d, 0xcf, 0x9f, 0x0a, 0xdf, 0x07, 0x74, 0x9c, 0xee, 0xe0, 0x62, 0xdb, 0xb6,
	0xcf, 0x64, 0x48, 0xa1, 0xeb, 0xe9, 0xcd, 0xa1, 0xc8, 0xe0, 0x74, 0x34, 0x5c, 0x1c, 0x24, 0x27,
	0x9b, 0x28, 0xbf, 0x94, 0x13, 0x5f, 0x4e, 0x49, 0xb5, 0xe7, 0xd2, 0x1b, 0x88, 0xf6, 0xd7, 0xfe,
	0x4b, 0x21, 0x60, 0xc1, 0xf8, 0xc1, 0x71, 0x90, 0x04, 0x9b, 0x73, 0xe5, 0xeb, 0x34, 0x87, 0xe5,
	0xac, 0xc7, 0x0a, 0xc2, 0xc6, 0x1c, 0x88, 0xb0, 0x31, 0x3f, 0x4e, 0xf8, 0xeb, 0xe4, 0x5f, 0x01,
	0x2c, 0x46, 0x49, 0x6c, 0x01, 0x4a, 0x8b, 0x9a, 0xd1, 0x9f, 0xe2, 0x7f, 0xe6, 0xf1, 0x8d, 0xd7,
	0xc7, 0x27, 0x15, 0x0f, 0x10, 0x59, 0xd4, 0xe6, 0xb0, 0xaa, 0x98, 0x93, 0xd3, 0x40, 0xd6, 0x57,
	0xb3, 0xa7, 0x3f, 0xd9, 0xec, 0x92, 0x97, 0xeb, 0xaa, 0xe1, 0x7a, 0x28, 0x64, 0x49, 0x5d, 0xf6,
	0x54, 0x0f, 0x45, 0xad, 0xbb, 0x5b, 0xa5, 0x9d, 0x6e, 0xb3, 0x8a, 0x1c, 0xda, 0xe2, 0xcc, 0x87,
	0x7e, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x60, 0x41, 0x5b, 0x82, 0x01, 0x00, 0x00,
}
